# Generated by Django 4.2.4 on 2023-08-28 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Master",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Email", models.EmailField(max_length=254, unique=True)),
                ("Password", models.CharField(max_length=12)),
                ("IsActive", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "master",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ProfileImage",
                    models.FileField(default="avatar.png", upload_to="profiles/"),
                ),
                ("FullName", models.CharField(blank=True, max_length=25, null=True)),
                (
                    "Gender",
                    models.CharField(
                        choices=[("m", "male"), ("f", "female")], max_length=2
                    ),
                ),
                ("BirthDate", models.DateField(default="2000-01-01")),
                ("Country", models.CharField(blank=True, max_length=25, null=True)),
                ("State", models.CharField(blank=True, max_length=25, null=True)),
                ("City", models.CharField(blank=True, max_length=25, null=True)),
                ("Address", models.TextField(blank=True, max_length=255, null=True)),
                (
                    "Master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resumeApp.master",
                    ),
                ),
            ],
            options={
                "db_table": "UserProfile",
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("SkillName", models.CharField(max_length=25)),
                (
                    "Level",
                    models.IntegerField(
                        choices=[
                            ("begginer", 40),
                            ("intermediate", 65),
                            ("advance", 100),
                        ]
                    ),
                ),
                (
                    "UserProfile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resumeApp.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": "skill",
            },
        ),
        migrations.CreateModel(
            name="Reference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FullName", models.CharField(blank=True, max_length=50, null=True)),
                ("Company", models.CharField(blank=True, max_length=50, null=True)),
                ("Email", models.EmailField(max_length=254, unique=True)),
                ("Mobile", models.CharField(max_length=10)),
                (
                    "UserProfile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resumeApp.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": "reference",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("EndDate", models.DateField(auto_created=True)),
                ("StartDate", models.DateField(auto_created=True)),
                (
                    "ProjectTitle",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("Company", models.CharField(blank=True, max_length=50, null=True)),
                ("IsCompleted", models.BooleanField(default=False)),
                (
                    "UserProfile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resumeApp.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": "project",
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("EndDate", models.DateField(auto_created=True)),
                ("StartDate", models.DateField(auto_created=True)),
                ("JobTitle", models.CharField(blank=True, max_length=50, null=True)),
                ("Company", models.CharField(blank=True, max_length=50, null=True)),
                ("IsCompleted", models.BooleanField(default=False)),
                (
                    "UserProfile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resumeApp.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": "experience",
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("EndDate", models.DateField(auto_created=True)),
                ("StartDate", models.DateField(auto_created=True)),
                (
                    "BoardUniversity",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("IsCompleted", models.BooleanField(default=False)),
                (
                    "UserProfile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resumeApp.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": "education",
            },
        ),
    ]
