# Generated by Django 4.2.4 on 2023-09-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumeApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="Description",
            field=models.TextField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
