# Generated by Django 4.2.4 on 2023-10-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumeApp", "0002_experience_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="UserID",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
